### ISSUE TITLE
alt_file doesn't have attribute name

### ISSUE THREAD

**Issue by kparasch** [xsuite/xaux#8]
https://github.com/xsuite/xaux/blob/94ccf16df638b7e7aa7b281cf1d1913422b264d1/xaux/protectfile.py#L443

```
Traceback (most recent call last):
  File "/srv/Template_LHCIT_ecloud_buildup/combine.py", line 77, in <module>
    with ProtectFile(triplet_path, 'r+b', backup=False, wait=1, eos_url=args.eos_url) as pf:
  File "/usr/local/xsuite/miniforge3/lib/python3.10/site-packages/xaux/protectfile.py", line 359, in __exit__
    self.mv_temp()
  File "/usr/local/xsuite/miniforge3/lib/python3.10/site-packages/xaux/protectfile.py", line 394, in mv_temp
    self.restore()
  File "/usr/local/xsuite/miniforge3/lib/python3.10/site-packages/xaux/protectfile.py", line 419, in restore
    print(f"Saved calculation results in {alt_file.name}.")
AttributeError: 'str' object has no attribute 'name'
```

alt_file doesn't have attribute name, at least when eos_url is provided, in which case it is a string.

**Comment by freddieknets** [comment]
Fixed in rewrite
